# Install everything you need for scoop








# This make sure you run as Administrator
if (-NOT ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator"))
{
  $arguments = "& '" +$myinvocation.mycommand.definition + "'"
  Start-Process powershell -Verb runAs -ArgumentList $arguments
  Break
}

# Make sure this can install PS modules
Set-ExecutionPolicy RemoteSigned
#Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process

# Command to create a PowerShell profile
New-Item -path $profile -type file -force

# Install windows terminal preview
winget install microsoft.windowsterminal.preview
winget uninstall microsoft.windowsterminal

# 执行安装命令 (admin)
iex "& {$(iwr -useb https://get.scoop.sh)} -RunAsAdmin"

# 执行安装命令 (non admin)
# iwr -useb https://get.scoop.sh | iex
# iwr -useb https://raw.githubusercontent.com/ScoopInstaller/Install/master/install.ps1 | iex

# 更换scoop的repo地址

# official repo
scoop config SCOOP_REPO 'https://github.com/ScoopInstaller/Scoop'

# backup repos
# scoop config SCOOP_REPO 'https://github.com/Ash258/Scoop-Core'

# scoop 用 git 拉取 bucket, 但 git 不走 Windows 系统代理 (WinINET).
# 若本机开了 Clash Verge 之类的代理, 必须显式告诉 git, 否则会出现
# "Could not resolve host: github.com" 或 "Recv failure: Connection was reset".
# 这里读取系统代理并写入 ~/.gitconfig_local (被 .gitconfig 的 [include] 引用),
# 这样代理端口变化时不用改 dotfiles 仓库。
$inet = Get-ItemProperty "HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings" -ErrorAction SilentlyContinue
if ($inet -and $inet.ProxyEnable -eq 1 -and $inet.ProxyServer) {
    $proxy = "http://$($inet.ProxyServer)"
    $local = "$env:USERPROFILE\.gitconfig_local"
    Write-Host "system proxy detected: $proxy"
    @"
# Machine-specific git config, pulled in by [include] in .gitconfig
# Generated by initial_scoop.ps1 from the Windows system proxy setting.

[http]
	proxy = $proxy
[https]
	proxy = $proxy
"@ | Set-Content -Path $local -Encoding UTF8
    git config --global http.proxy $proxy
    git config --global https.proxy $proxy
} else {
    Write-Host "no system proxy detected, git will connect directly"
}

# 拉取新库地址
scoop update

# must-have apps
scoop install git aria2 dark

# aria2
scoop config aria2--enabled true
scoop config aria2-warning-enabled false

# must-have buckets
scoop bucket add main
scoop bucket add apps "https://github.com/kkzzhizhou/scoop-apps"
scoop bucket add im-select "https://github.com/daipeihust/im-select"

# repair-buckets.ps1 修复 bucket 仓库
# scoop 在 bucket 里做 merge 时若网络中断, 会留下未完成的 merge, 之后每次
# scoop update 都报 "Pulling is not possible because you have unmerged files".
# bucket 是纯上游镜像, 本地改动没有价值, 直接重置到 origin/master 即可.
& "$PSScriptRoot\utils\repair-scoop-buckets.ps1"

<#
scoop bucket add extras
scoop bucket add versions
scoop bucket add nightlies
scoop bucket add nirsoft
scoop bucket add php
scoop bucket add nerd-fonts
scoop bucket add nonportable
scoop bucket add java
scoop bucket add games
scoop bucket add jetbrains

scoop bucket add scoopet "https://github.com/ivaquero/scoopet.git"
scoop bucket add portablesoft 'https://github.com/shenbo/portablesoft'
#>

# improve scoop usability
scoop install scoop-search scoop-completion komorebi hack-nf
# install preloaded list
# scoop import importable_packages.json
